export default [
  {
    id: 1,
    firstName: 'Velasquez',
    lastName: 'Terry',
    role: 'user',
    email: 'email@paystack.com',
  },
  {
    id: 2,
    firstName: 'Rosa',
    lastName: 'Daugherty',
    role: 'user',
    email: 'email@paystack.com',
  },
  {
    id: 3,
    firstName: 'Virgie',
    lastName: 'Dawson',
    role: 'user',
    email: 'email@paystack.com',
  },
  {
    id: 4,
    firstName: 'Howell',
    lastName: 'Montgomery',
    role: 'user',
    email: 'email@paystack.com',
  },
  {
    id: 5,
    firstName: 'Chang',
    lastName: 'Oneil',
    role: 'user',
    email: 'email@paystack.com',
  },
  {
    id: 6,
    firstName: 'Tommie',
    lastName: 'Hamilton',
    role: 'user',
    email: 'email@paystack.com',
  },
  {
    id: 7,
    firstName: 'Griffith',
    lastName: 'Boyd',
    role: 'user',
    email: 'email@paystack.com',
  },
  {
    id: 8,
    firstName: 'Gardner',
    lastName: 'Contreras',
    role: 'user',
    email: 'email@paystack.com',
  },
  {
    id: 9,
    firstName: 'Cantu',
    lastName: 'Clay',
    role: 'user',
    email: 'email@paystack.com',
  },
  {
    id: 10,
    firstName: 'Daisy',
    lastName: 'Gilliam',
    role: 'user',
    email: 'email@paystack.com',
  },
  {
    id: 11,
    firstName: 'Banks',
    lastName: 'Berger',
    role: 'user',
    email: 'email@paystack.com',
  },
  {
    id: 12,
    firstName: 'Best',
    lastName: 'Melendez',
    role: 'user',
    email: 'email@paystack.com',
  },
  {
    id: 13,
    firstName: 'Merrill',
    lastName: 'Solomon',
    role: 'user',
    email: 'email@paystack.com',
  },
  {
    id: 14,
    firstName: 'Bridges',
    lastName: 'Moses',
    role: 'user',
    email: 'email@paystack.com',
  },
  {
    id: 15,
    firstName: 'Carr',
    lastName: 'Snider',
    role: 'user',
    email: 'email@paystack.com',
  },
  {
    id: 16,
    firstName: 'Aurelia',
    lastName: 'Randolph',
    role: 'user',
    email: 'email@paystack.com',
  },
  {
    id: 17,
    firstName: 'Castro',
    lastName: 'Farmer',
    role: 'user',
    email: 'email@paystack.com',
  },
  {
    id: 18,
    firstName: 'Christian',
    lastName: 'White',
    role: 'user',
    email: 'email@paystack.com',
  },
];
